//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAhorcadoCliente.WSReferencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/WsAhorcado")]
    [System.SerializableAttribute()]
    public partial class Palabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuevaPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuevaPalabraGuionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vidasRestantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuevaPalabra {
            get {
                return this.nuevaPalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.nuevaPalabraField, value) != true)) {
                    this.nuevaPalabraField = value;
                    this.RaisePropertyChanged("nuevaPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuevaPalabraGuion {
            get {
                return this.nuevaPalabraGuionField;
            }
            set {
                if ((object.ReferenceEquals(this.nuevaPalabraGuionField, value) != true)) {
                    this.nuevaPalabraGuionField = value;
                    this.RaisePropertyChanged("nuevaPalabraGuion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vidasRestantes {
            get {
                return this.vidasRestantesField;
            }
            set {
                if ((object.ReferenceEquals(this.vidasRestantesField, value) != true)) {
                    this.vidasRestantesField = value;
                    this.RaisePropertyChanged("vidasRestantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSReferencia.IWSAhorcado")]
    public interface IWSAhorcado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAhorcado/ObtenerPalabra", ReplyAction="http://tempuri.org/IWSAhorcado/ObtenerPalabraResponse")]
        WebAppAhorcadoCliente.WSReferencia.Palabra ObtenerPalabra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAhorcado/ObtenerPalabra", ReplyAction="http://tempuri.org/IWSAhorcado/ObtenerPalabraResponse")]
        System.Threading.Tasks.Task<WebAppAhorcadoCliente.WSReferencia.Palabra> ObtenerPalabraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAhorcado/ValidarLetra", ReplyAction="http://tempuri.org/IWSAhorcado/ValidarLetraResponse")]
        WebAppAhorcadoCliente.WSReferencia.Palabra ValidarLetra(string Letra, string Palabra, string PalabraGuion, string VidasRestantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAhorcado/ValidarLetra", ReplyAction="http://tempuri.org/IWSAhorcado/ValidarLetraResponse")]
        System.Threading.Tasks.Task<WebAppAhorcadoCliente.WSReferencia.Palabra> ValidarLetraAsync(string Letra, string Palabra, string PalabraGuion, string VidasRestantes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSAhorcadoChannel : WebAppAhorcadoCliente.WSReferencia.IWSAhorcado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAhorcadoClient : System.ServiceModel.ClientBase<WebAppAhorcadoCliente.WSReferencia.IWSAhorcado>, WebAppAhorcadoCliente.WSReferencia.IWSAhorcado {
        
        public WSAhorcadoClient() {
        }
        
        public WSAhorcadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAhorcadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAhorcadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAhorcadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAppAhorcadoCliente.WSReferencia.Palabra ObtenerPalabra() {
            return base.Channel.ObtenerPalabra();
        }
        
        public System.Threading.Tasks.Task<WebAppAhorcadoCliente.WSReferencia.Palabra> ObtenerPalabraAsync() {
            return base.Channel.ObtenerPalabraAsync();
        }
        
        public WebAppAhorcadoCliente.WSReferencia.Palabra ValidarLetra(string Letra, string Palabra, string PalabraGuion, string VidasRestantes) {
            return base.Channel.ValidarLetra(Letra, Palabra, PalabraGuion, VidasRestantes);
        }
        
        public System.Threading.Tasks.Task<WebAppAhorcadoCliente.WSReferencia.Palabra> ValidarLetraAsync(string Letra, string Palabra, string PalabraGuion, string VidasRestantes) {
            return base.Channel.ValidarLetraAsync(Letra, Palabra, PalabraGuion, VidasRestantes);
        }
    }
}
